title: Al Gill, PhD 
logo: "/images/Al_4_Gits.jpg?raw=true" # your photo (or logo) here
description:  
  Group Project (Cambridge Spark Bootcamp) 
  <br><br>
  Why are VC returns pareto distributed?
  <br><br>
  <a href="https://www.linkedin.com/in/alasdairgill/"> View My LinkedIn Profile </a> 
  
theme: jekyll-theme-minimal
