title: Al Gill, PhD 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:  
  Group Project from Cambridge Spark Bootcamp 
  <br><br>
  Why are VC returns pareto distributed?
  <br><br>
  <a href="https://www.linkedin.com/in/alasdairgill/"> View My LinkedIn Profile </a> 
  
theme: jekyll-theme-minimal
